### PR TITLE
changed tile icons colors to white

### LINKED ISSUE #7: Color on transparent tile
"8c" on transparent tile should be white (instead of black).

### PR DESCRIPTION
**Pull request by gautamkrishnar**
changed tile icons colors to white
fixes:#7

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
@christophwille just checking out!
Have you stopped maintaining this project?

**Comment by christophwille** [comment]
It should be converted to UWP to start with... but given potential (small) audience I couldn't yet convince myself to invest the time necessary.

**Comment by gautamkrishnar** [comment]
@christophwille  I am happy to contribute to this project on my leisure time. I am a regular user of your app. You can add me as a contributor if you like.

**Comment by gautamkrishnar** [comment]
I think this pull request is good to merge. Shall i have to make any more changes?

**Comment by gautamkrishnar** [comment]
just closing this one

**Pull request closed without merging**
